### ISSUE TITLE
Possible misuse of admin privileges?

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ffnbsee-website#11] opened 2020-02-24 00:11 UTC
commit 024f079c11205a6cccb0ed76f0b99a268672a3ff ohne pullrequest.

 @xperimental bitte erklären!

**Comment by xperimental** [comment] 2020-02-24 23:02
Hello @DO1JLR, thanks for your comment. I did multiple changes during the weekend on both websites of ffbsee and was in direct contact with other people (most notably @mart-ffbsee ) during that time. I had also asked him if it was okay for him if I try something directly on master before doing the change, because I was not sure if it worked on the first try (it was not the commit you mentioned).

While this did technically not satisfy our constraint to have pull-requests, I and apparently also the others deemed this okay in this case because we were already talking about it anyway. But I am open to hearing other opinions as well.

**Comment by DO1JLR** [comment] 2020-02-25 06:37
Was in irgend welchen privaten chats ausgetauscht wird rechtfertigt pull-requests auf den master **nicht**!

Besprech das doch - wenn es schon nicht github/gitea ist - auf der mailingliste oder im public chat!

**Comment by DO1JLR** [comment] 2020-02-25 07:54
Sind die community guidlines also nur optional oder dürfen auf grund von privaten chatbeiträgen von mit nicht definierten personen jederzeit ignoriert werden?

Gib deine Adminrechte ab bis das geklärt ist!

**Comment by xperimental** [comment] 2020-02-25 10:37
I guess we can close this as a duplicate of ffbsee/ffbsee-webseite#120, so that we do not need to write everything twice...

**Closed as completed by xperimental** 2020-02-25 10:37 UTC
